apiVersion: v1
kind: Service
metadata:
  annotations:
    description: svc-grpc-dubbo-proxy
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-2tdvvzeh
  name: svc-grpc-dubbo-proxy
  namespace: eqxiu-ops
spec:
  ports:
    - name: port-lp
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    qcloud-app: grpc-dubbo-proxy
  sessionAffinity: None
  type: LoadBalancer