apiVersion: v1
kind: Service
metadata:
  annotations:
    description: svc-grpc-dubbo-proxy
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-2tdvvzeh
  name: svc-grpc-dubbo-proxy
  namespace: eqxiu-ops
spec:
  ports:
    - name: port-lp
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    qcloud-app: grpc-dubbo-proxy
  sessionAffinity: None
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: grpc-dubbo-proxy
  labels:
    qcloud-app: grpc-dubbo-proxy
  name: grpc-dubbo-proxy
  namespace: eqxiu-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      qcloud-app: grpc-dubbo-proxy
  template:
    metadata:
      labels:
        qcloud-app: grpc-dubbo-proxy
    spec:
      containers:
        - name: grpc-dubbo-proxy
          image: ccr.ccs.tencentyun.com/eqxiu/grpc-dubbo-proxy
          command:
          - "java"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-Xms1024m"
          - "-Xmx1024m"
          - "-XX:+UseG1GC"
#          - "-XX:ActiveProcessorCount=8"
#          - "-XX:+UseStringDeduplication"
#          - "-Dfile.encoding=UTF-8"
#          - "-Dsun.jnu.encoding=UTF-8"
#          - "-Djava.awt.headless=true"
          - "-jar"
          - "/app.jar"
          env:
          - name: 'spring.profiles.active'
            value: 'product'
#          - name: 'logging.level.org.apache.dubbo.config'
#            value: 'ERROR'
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 5050
          readinessProbe:
            tcpSocket:
              port: 5050
          resources:
            limits:
              memory: 1.5Gi
              cpu: "1"
            requests:
              cpu: "1"
              memory: 1.5Gi
          securityContext:
            privileged: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate