grpc:
  server:
    port: 5050
proxy:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

dubbo:
  application:
    qos:
      enable: false
    