grpc:
  server:
    port: 5050
proxy:
  registry:
    address: zookeeper://zk1.eqxiu.com:2181?backup=zk2.eqxiu.com:2181,zk3.eqxiu.com:2181
  metadata-report:
    address: zookeeper://zk1.eqxiu.com:2181?backup=zk2.eqxiu.com:2181,zk3.eqxiu.com:2181

dubbo:
  application:
    qos:
      enable: false
    