// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clazz_method_param.proto

package org.apache.dubbo.proxy.proto;

public final class ClazzMethodParam {
  private ClazzMethodParam() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_ProxyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_ProxyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_ProxyReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_ProxyReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/clazz_method_param.proto\022\005dubbo\"" +
      "\211\001\n\014ProxyRequest\022\023\n\013application\030\001 \001(\t\022\025\n" +
      "\rinterfaceName\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\r\n" +
      "\005group\030\004 \001(\t\022\016\n\006method\030\005 \001(\t\022\r\n\005types\030\006 " +
      "\003(\t\022\016\n\006values\030\007 \001(\t\"\034\n\nProxyReply\022\016\n\006res" +
      "ult\030\001 \001(\t2G\n\014ProxyService\0227\n\013InvokeProxy" +
      "\022\023.dubbo.ProxyRequest\032\021.dubbo.ProxyReply" +
      "\"\000B\"\n\034org.apache.dubbo.proxy.protoH\001P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dubbo_ProxyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dubbo_ProxyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_ProxyRequest_descriptor,
        new java.lang.String[] { "Application", "InterfaceName", "Version", "Group", "Method", "Types", "Values", });
    internal_static_dubbo_ProxyReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dubbo_ProxyReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_ProxyReply_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
