// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clazz_method_param.proto

package org.apache.dubbo.proxy.proto;

public interface ProxyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dubbo.ProxyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string application = 1;</code>
   * @return The application.
   */
  java.lang.String getApplication();
  /**
   * <code>string application = 1;</code>
   * @return The bytes for application.
   */
  com.google.protobuf.ByteString
      getApplicationBytes();

  /**
   * <code>string interfaceName = 2;</code>
   * @return The interfaceName.
   */
  java.lang.String getInterfaceName();
  /**
   * <code>string interfaceName = 2;</code>
   * @return The bytes for interfaceName.
   */
  com.google.protobuf.ByteString
      getInterfaceNameBytes();

  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string group = 4;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 4;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string method = 5;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 5;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>repeated string types = 6;</code>
   * @return A list containing the types.
   */
  java.util.List<java.lang.String>
      getTypesList();
  /**
   * <code>repeated string types = 6;</code>
   * @return The count of types.
   */
  int getTypesCount();
  /**
   * <code>repeated string types = 6;</code>
   * @param index The index of the element to return.
   * @return The types at the given index.
   */
  java.lang.String getTypes(int index);
  /**
   * <code>repeated string types = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the types at the given index.
   */
  com.google.protobuf.ByteString
      getTypesBytes(int index);

  /**
   * <code>string values = 7;</code>
   * @return The values.
   */
  java.lang.String getValues();
  /**
   * <code>string values = 7;</code>
   * @return The bytes for values.
   */
  com.google.protobuf.ByteString
      getValuesBytes();
}
