// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clazz_method_param.proto

package org.apache.dubbo.proxy.proto;

public interface ProxyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dubbo.ProxyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
